name: Update Workflows

on:
  push:
    branches:
      - main  # Adjust branch if necessary

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run update-workflows.js
      run: node scripts/update-workflows.js

    - name: Commit and push updated workflows
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .github/workflows/*.yml
        git commit -m "Update workflows with current template options"
        git push
      continue-on-error: true
