name: Site Process

on:
  workflow_dispatch:
    inputs:
      site:
        description: Select the site to process
        required: true
        type: choice
        options:
          - immediate-trader.org
          - trackinggate.pro

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Extract domain from metadata.json and set repo name
        id: extract_domain
        run: |
          METADATA_FILE="templates/${{ github.event.inputs.site }}/metadata.json"
          if [ -f "$METADATA_FILE" ]; then
            echo "metadata.json found at $METADATA_FILE"
            NEW_URL=$(jq -r '.newUrl // empty' $METADATA_FILE)
            if [ -z "$NEW_URL" ]; then
              echo "Error: Could not extract newUrl from metadata.json"
              exit 1
            else
              REPO_NAME="${NEW_URL}"
              echo "Repository will be named: $REPO_NAME"
              echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
            fi
          else
            echo "Error: metadata.json not found at $METADATA_FILE"
            exit 1
          fi

      - name: Create new folder and copy contents
        run: |
          mkdir -p ${{ env.REPO_NAME }}
          cp -r templates/${{ github.event.inputs.site }}/* ${{ env.REPO_NAME }}/
        shell: bash

      - name: Run repository setup
        run: |
          chmod +x ./scripts/repo_setup.sh
          ./scripts/repo_setup.sh ${{ env.REPO_NAME }} ${{ secrets.PAT_TOKEN }}
        shell: bash

      - name: Run Pages setup
        run: |
          chmod +x ./scripts/pages_setup.sh
          ./scripts/pages_setup.sh ${{ env.REPO_NAME }} ${{ secrets.PAT_TOKEN }} ${{ env.REPO_NAME }}
        shell: bash
