name: Update README

on:
  push:
    branches:
      - main  # Adjust branch if necessary

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'  # Use Node.js LTS version

    - name: Install dependencies
      run: npm install

    - name: Run update-readme.js
      run: node scripts/update-readme.js

    - name: Commit and push updated README
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Update README with current template links"
        git push
      continue-on-error: true
